services:

  owui:
    image: ghcr.io/open-webui/open-webui:v0.4.2
    expose:
      - 8080
    ports:
      - 127.0.0.1:3000:8080
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owui.rule=Host(`chat.brace.tools`)"
      - "traefik.http.routers.owui.entrypoints=websecure"
      - "traefik.http.routers.owui.tls=true"
      - "traefik.http.routers.owui.tls.certresolver=myresolver"
    volumes:
      - owui-data:/app/backend/data
      - ./book:/book:ro
      - ./prompts.json:/app/backend/prompts.json:ro
      - ./models.json:/app/backend/models.json:ro
      - ./brace-logo-symbol.png:/app/backend/brace-logo-symbol.png:ro
      - ./brace-system-prompt.md:/app/backend/brace-system-prompt.md:ro
      - ./functions:/functions:ro
      - ./functions.json:/app/backend/functions.json:ro
      - ./custom_start.sh:/app/backend/custom_start.sh:ro
      - ./custom_start.py:/app/backend/custom_start.py:ro
    entrypoint: ["bash", "/app/backend/custom_start.sh"]
    restart: always
    env_file:
      - keys.env
      - oauth.env
    environment:
      WEBUI_NAME: Brace
      ENABLE_SIGNUP: false
      ENABLE_OAUTH_SIGNUP: true
      ENABLE_LOGIN_FORM: false
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      DEFAULT_USER_ROLE: user
      OPENID_PROVIDER_URL: https://accounts.google.com/.well-known/openid-configuration
      USER_PERMISSIONS_CHAT_DELETION: false
      USER_PERMISSIONS_CHAT_EDITING: false
      USER_PERMISSIONS_CHAT_TEMPORARY: false
      ENABLE_MESSAGE_RATING: false
      ENABLE_COMMUNITY_SHARING: false
      ENABLE_OLLAMA_API: false
      ENABLE_OPENAI_API: true
      AUDIO_STT_ENGINE: openai
      AUDIO_TTS_ENGINE: openai
      RAG_EMBEDDING_ENGINE: openai
      ENABLE_MODEL_FILTER: true
      MODEL_FILTER_LIST: brace
      DEFAULT_MODELS: brace
      RESET_CONFIG_ON_START: true

networks:
  web:
    name: web
    external: true

volumes:
  owui-data:
